### PR TITLE
Add non-NULL asserts to CMSG_* returns, null-initialize AncillaryBuf

### PR DESCRIPTION
**Pull request by domenukk**
Added two checks for NULL returns and one zero-ing that is technically more correct

### CODE REVIEW

**Review by tormol — COMMENTED** [review]
Would be nice to describe the changes in the commit message in addition to the PR.

I see `CMSG_NXTHDR()` requires the buffer to be zero-initialized, so that's a good catch.

**Comment by tormol** [comment]
I've fixed the CI failure, please rebase.

**Comment by domenukk** [comment]
Rebased and switched to `assert`

**Comment by tormol** [comment]
Thanks!

**Comment by tormol** [comment]
Released as 0.2.7 and 0.3.0.

**Pull request merged**
